In [1]:
import numpy as np

In [31]:
x = np.arange(25).reshape(5, 5)

In [32]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
x[2][2]

12

In [34]:
x[2,2]

12

In [37]:
x[2:4,3:] # i= recebe de 0 a n linhas e j= recebe de 0 a n colunas

array([[13, 14],
       [18, 19]])

In [39]:
y = np.arange(1,20)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [43]:
h = y>12
h

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [46]:
y[y>12] #Valores que sao maiores que 12

array([13, 14, 15, 16, 17, 18, 19])

In [50]:
y[y % 2 == 0] #Valores que tem resto da divisao igual a 0

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
h = np.arange(10)
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.sin(h)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [58]:
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [82]:
a = np.array([1,2,4,5,7,9])
b = np.array([1,2,3,4,5,6,7,8,9])
c = np.array(["David", "Marcos", "Andre","Lucas"])
d = np.array(["David", "Pedro", "Lucas", "Jean", "Igor"])

In [76]:
a[(a>5) & (a<10)]

array([6, 7, 8, 9])

In [80]:
np.intersect1d(a,b) #Elementos que estão em ambas as listas

array([1, 2, 4, 5, 7, 9])

In [96]:
np.intersect1d(c,d)

array(['David', 'Lucas'], dtype='<U6')