In [1]:
import numpy as np

In [4]:
x = np.arange(1, 21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
x[4:10]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
x[7:10] = 40
x

array([ 1,  2,  3,  4,  5,  6,  7, 40, 40, 40, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
x[7:10]

array([40, 40, 40])

In [10]:
y = x.copy() #Copia a lista x para a variável y

In [11]:
y

array([ 1,  2,  3,  4,  5,  6,  7, 40, 40, 40, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])